---
- hosts: localhost
  connection: local
  become: false
  gather_facts: false
  # Define the backend configuration at init
  tasks:
    - name: Terraform Plan
      terraform:
        project_path: '../terraform'
        force_init: true
        state: 'planned'
        plan_file: '/ansible/playbooks/myplan.tfstate'
        variables:
          environment: "{{env}}"
        backend_config:
          region: "eu-west-1"
          bucket: "manuscript-tf-ansible-{{env}}-tfstate"
          key: "{{env}}-state.tfstate"
      register: terraform_plan
      when: not  destroy|bool
    - debug:
        var=terraform_plan
    - name: Terraform Apply
      terraform:
        project_path: '../terraform'
        force_init: true
        variables:
          environment: "{{env}}"
        backend_config:
          region: "eu-west-1"
          bucket: "{{env}}-tfstate"
          key: "{{env}}-state.tfstate"
      register: terraform_apply
      when: not destroy|bool and not plan_only|bool
    - debug:
        var=terraform_apply
    - name: Destroy Terraform infra
      terraform:
        project_path: '../terraform'
        purge_workspace: 'yes'
        state: 'absent'
        force_init: true
        variables:
          environment: "{{env}}"

        backend_config:
          region: "eu-west-1"
          bucket: "{{env}}-tfstate"
          key: "{{env}}-state.tfstate"
      register: terraform_destroy
      when: destroy|bool
    - debug:
        var: terraform_destroy