---
- hosts: localhost
  connection: local
  become: false
  gather_facts: false
  # Define the backend configuration at init
  tasks:
    - name: Terraform Apply
      terraform:
        project_path: '../terraform'
        force_init: true
        variables:
          environment: "{{env}}"
        backend_config:
          region: "eu-west-1"
          bucket: "manuscript-tf-ansible-{{env}}-tfstate"
          key: "{{env}}-state.tfstate"
      register: terraform_apply
    - debug:
        var=terraform_apply