---
# Define the backend configuration at init
- terraform:
    project_path: '../terraform/{{env}}'
    state: "{{ state }}"
    force_init: true

    backend_config:
      region: "eu-west-1"
      bucket: "{{env}}-tfstate"
      key: "{{env}}-state.tfstate"