---
- hosts: localhost
  connection: local
  become: false
  gather_facts: false
  # Define the backend configuration at init
  tasks:
    - debug:
        var=destroy
    - name: Capturing Terraform Command
      terraform:
        project_path: '../terraform/modules'
        force_init: true
        variables:
          environment: "{{env}}"

        backend_config:
          region: "eu-west-1"
          bucket: "{{env}}-tfstate"
          key: "{{env}}-state.tfstate"
      register: terraform_plan
      when: destroy
    - debug:
        var=terraform_plan
    - name: Destroy Terraform infra
      terraform:
        project_path: '../terraform/modules'
        purge_workspace: 'yes'
        state: 'absent'
        force_init: true
        variables:
          environment: "{{env}}"

        backend_config:
          region: "eu-west-1"
          bucket: "{{env}}-tfstate"
          key: "{{env}}-state.tfstate"
      register: terraform_destroy
      when: destroy|bool
    - debug:
        var: not destroy