---
- hosts: localhost
  connection: local
  become: false
  gather_facts: false
# Define the backend configuration at init
  tasks:
    - name: Capturing Terraform Command
      terraform:
        project_path: '../terraform/{{env}}'
        force_init: true
        variables:
          env: "{{env}}"

        backend_config:
          region: "eu-west-1"
          bucket: "{{env}}-tfstate"
          key: "{{env}}-state.tfstate"