---
- hosts: localhost
  connection: local
  become: false
  gather_facts: false
# Define the backend configuration at init
  tasks:
    - name: Capturing Terraform Command
      terraform:
        project_path: '../terraform/modules'
        force_init: true
        state: 'planned'
        plan_file: "{{ project_dir }}/myplan.tfplan"
        variables:
          environment: "{{env}}"

        backend_config:
          region: "eu-west-1"
          bucket: "{{env}}-tfstate"
          key: "{{env}}-state.tfstate"
      register: terraform
      check_mode: yes
      when: not destroy|bool
    - debug:
        var: terraform
    - name: Destroy Terraform infra
      terraform:
        project_path: '../terraform/modules'
        purge_workspace: 'yes'
        state: 'absent'
        force_init: true
        variables:
          environment: "{{env}}"

        backend_config:
          region: "eu-west-1"
          bucket: "{{env}}-tfstate"
          key: "{{env}}-state.tfstate"
      register: terraform_destroy
      when: destroy|bool
    - debug:
        var: terraform_destroy